export const importCategoryMap: { [key: string]: string } = {
	"utils/": "UTILS",
	"components/common-styles/": "STYLES",
	"styles/": "STYLES",
	".styles": "STYLES",
	"theme/": "STYLES",
	"components/": "COMPONENTS",
	Component: "COMPONENTS",
	"contexts/": "CONTEXTS",
	".scss": "STYLES",
	"types/": "TYPES",
	"enums/": "ENUMS",
	"assets/icons": "SVG's",
	"navigation/": "NAVIGATION",
	".ds": "DATA SERVICES",
	"/data-service": "DATA SERVICES",
	".jpg": "IMAGES",
	".png": "IMAGES",
	".jpeg": "IMAGES",
	"api/": "API SERVICES",
	"services/": "SERVICES",
	".service": "SERVICES",
	component: "COMPONENTS",
	".tsx": "COMPONENTS",
	Image: "COMPONENTS",
	constants: "UTILS",
	"react-native": "REACT NATIVE",
	React: "REACT",
	useState: "REACT",
	useEffect: "REACT",
	useRouter: "REACT",
	useRef: "REACT",
	useContext: "REACT",
	express: "MODULES",
	module: "MODULES",
	expo: "MODULES",
	model: "MODELS",
	ionic: "MODULES",
	angular: "MODULES",
	"/controllers": "CONTROLLERS",
	".controller": "CONTROLLERS",
	"/routes": "ROUTES",
	".route": "ROUTES",
	"/dummy-data": "DUMMY DATA",
	"jwt": "MODULES",
	"bcrypt": "MODULES",
	"mongo": "MODULES",
	"dotenv": "MODULES",
	"pg-promise": "MODULES",
	"body-parser": "MODULES",
	"cors": "MODULES",
	"path": "MODULES",
	"fs": "MODULES",
	"mongoose": "MODULES",
	"sql": "MODULES",
	"axios": "MODULES"
};

export const importCategories = [
	"REACT",
	"REACT NATIVE",
	"MODULES",
	"MODELS",
	"TYPES",
	"ENUMS",
	"STYLES",
	"COMPONENTS",
	"ROUTES",
	"CONTROLLERS",
	"API SERVICES",
	"DATA SERVICES",
	"CONTEXTS",
	"SERVICES",
	"UTILS",
	"NAVIGATION",
	"OTHERS",
	"IMAGES",
	"SVG's",
	"DUMMY DATA",
];

export const importCategoriesWithVariations = [
	// Uppercase variations
	"REACT",
	"REACTT",
	"REACTJS",
	"REACT.JS",
	"REACTNATIVE",
	"RN",
	"REACTNATIVE",
	"REACT-NATIVE",
	"MODULES",
	"MODULE",
	"MODULE",
	"MODUL",
	"STYLES",
	"STYLE",
	"STYLES",
	"STLYES",
	"COMPONENTS",
	"COMPONENT",
	"COMPONENT",
	"COMP",
	"CMP",
	"RUOTE",
	"ROUTES",
	"ROUTE",
	"CONTROLLERS",
	"CONTROLERS",
	"CONTROLLER",
	"CONTROLER",
	"API SERVICES",
	"API SERVICE",
	"APISERVICES",
	"APIS",
	"DATA SERVICES",
	"DATA SERVICE",
	"DATASERVICE",
	"DATASERVICES",
	"CONTEXTS",
	"CONTEXT",
	"CONTEXT",
	"SERVICES",
	"SERVICE",
	"SERVICES",
	"SERVCES",
	"UTILS",
	"UTILS",
	"UTIL",
	"MODELS",
	"MODELS",
	"MODELS",
	"TYPES",
	"TYEPS",
	"TYPE",
	"TYPESCRIPT",
	"ENUMS",
	"ENMUS",
	"ENUMSS",
	"NAVIGATION",
	"NAVIGATON",
	"NAVIGATIONS",
	"OTHERS",
	"IMAGES",
	"IMAGS",
	"IMAGESS",
	"SVG'S",
	"SVGS",
	"SVG",
];
