export const importCategoryMap: { [key: string]: string } = {
	express: "MODULES",
	".css": "STYLES",
	".scss": "STYLES",
	module: "MODULES",
	model: "MODELS",
	ionic: "MODULES",
	angular: "MODULES",
	renderer: "MODULES",
	openBrowserAsync: "MODULES",
	useRouter: "REACT",
	"types/": "TYPES",
	".d.": "TYPES",
	router: "MODULES",
	jwt: "MODULES",
	bcrypt: "MODULES",
	mongo: "MODULES",
	dotenv: "MODULES",
	"pg-promise": "MODULES",
	"body-parser": "MODULES",
	cors: "MODULES",
	path: "MODULES",
	mongoose: "MODULES",
	sql: "MODULES",
	axios: "MODULES",
	".util": "UTILS",
	"utils/": "UTILS",
	"environmets/": "UTILS",
	environment: "UTILS",
	"components/common-styles/": "STYLES",
	"styles/": "STYLES",
	".styles": "STYLES",
	"theme/": "STYLES",
	Theme: "STYLES",
	"next/navigation": "NAVIGATION",
	"components/": "COMPONENTS",
	"contexts/": "CONTEXTS",
	"enums/": "ENUMS",
	fs: "MODULES",
	"assets/icons": "SVG's",
	"navigation/": "NAVIGATION",
	"/services/db": "DB",
	".ds": "DATA SERVICES",
	"/data-service": "DATA SERVICES",
	"/services/data": "DATA SERVICES",
	"/services/data/": "DATA SERVICES",
	".jpg": "IMAGES",
	".png": "IMAGES",
	".jpeg": "IMAGES",
	"api/": "API SERVICES",
	"services/": "SERVICES",
	".service": "SERVICES",
	component: "COMPONENTS",
	"next/": "COMPONENTS",
	".tsx": "COMPONENTS",
	Image: "COMPONENTS",
	constants: "CONSTANTS",
	"react-native-": "PLUGINS",
	"react-native": "REACT NATIVE",
	react: "REACT",
	React: "REACT",
	useState: "REACT",
	useEffect: "REACT",
	useRef: "REACT",
	useContext: "REACT",
	Component: "COMPONENTS",
	"/controllers": "CONTROLLERS",
	".controller": "CONTROLLERS",
	"/routes": "ROUTES",
	".route": "ROUTES",
	"-routing": "ROUTINGS",
	data: "DATA",
	"/data": "DATA",
	gorhom: "PLUGINS",
	expo: "PLUGINS",
	swipper: "PLUGINS",
	tween: "PLUGINS",
	slick: "PLUGINS",
	gsap: "PLUGINS",
	scrollTrigger: "PLUGINS",
	"/sections": "SECTIONS",
	".page": "PAGES",
	"screen/": "SCREENS",
	Screen: "SCREENS",
};

export const importCategories = [
	"REACT",
	"REACT NATIVE",
	"MODULES",
	"PLUGINS",
	"MODELS",
	"TYPES",
	"ENUMS",
	"STYLES",
	"COMPONENTS",
	"ROUTES",
	"CONTROLLERS",
	"API SERVICES",
	"DATA SERVICES",
	"CONTEXTS",
	"SERVICES",
	"DB",
	"CONSTANTS",
	"UTILS",
	"NAVIGATION",
	"OTHERS",
	"IMAGES",
	"SVG's",
	"SECTIONS",
	"DATA",
	"PAGES",
	"SCREENS",
	"ROUTINGS",
];

export const importCategoriesWithVariations = [
	// Uppercase variations
	"REACT",
	"REACTT",
	"REACTJS",
	"REACT.JS",
	"REACTNATIVE",
	"RN",
	"REACTNATIVE",
	"REACT-NATIVE",
	"MODULES",
	"MODULE",
	"MODULE",
	"MODUL",
	"STYLES",
	"STYLE",
	"STYLES",
	"STLYES",
	"COMPONENTS",
	"COMPONENT",
	"COMPONENT",
	"COMP",
	"CMP",
	"RUOTE",
	"ROUTES",
	"ROUTE",
	"CONTROLLERS",
	"CONTROLERS",
	"CONTROLLER",
	"CONTROLER",
	"API SERVICES",
	"API SERVICE",
	"APISERVICES",
	"APIS",
	"DATA SERVICES",
	"DATA SERVICE",
	"DATASERVICE",
	"DATASERVICES",
	"CONTEXTS",
	"CONTEXT",
	"CONTEXT",
	"SERVICES",
	"SERVICE",
	"SERVICES",
	"SERVCES",
	"DB",
	"DB's",
	"CONSTANT",
	"CONTSANTS",
	"CONSTANT",
	"CONSTANTES",
	"UTILS",
	"UTILS",
	"UTIL",
	"MODELS",
	"MODELS",
	"MODELS",
	"TYPES",
	"TYEPS",
	"TYPE",
	"TYPESCRIPT",
	"ENUMS",
	"ENMUS",
	"ENUMSS",
	"NAVIGATION",
	"NAVIGATON",
	"NAVIGATIONS",
	"OTHERS",
	"IMAGES",
	"IMAGS",
	"IMAGESS",
	"SVG'S",
	"SVGS",
	"SVG",
	"DATA",
	"DTA",
	"PLUGINS",
	"PLUGIN",
	"PLUGNS",
	"PLUGN",
	"SECTIONS",
	"SECTION",
	"PAGES",
	"PAGE",
	"SCEEN",
	"SCREE",
	"SCREEN",
	"SCREN",
	"ROUTEING",
	"ROUTIN",
	"ROUTINGS",
	"ROUTING",
];
